

MODEL:
  FEATURE_DIM: 32


INPUT:
  SIZE_TRAIN: [768,432]
  SIZE_TEST: [768,432]
  NEAR_FAR_SIZE: [5.0, 18.0, 1]
  USE_RGB: False

DATASETS:
  TRAIN: "/data/dataset/Wolf"
  FRAME_NUM: 1
  MASK: True
  CENTER: [540,960]
  SHIFT: 10
  MAXRATION: 0.5
  ROTATION: 0.0


SOLVER:
  OPTIMIZER_NAME: "Adam"
  BASE_LR: 0.00005
  WEIGHT_DECAY: 0.00002
  IMS_PER_BATCH: 3
  WARMUP_FACTOR: 0.333
  WARMUP_ITERS: 20
  WARMUP_METHOD: "linear"
  MAX_EPOCHS: 1500

TEST:
  IMS_PER_BATCH: 256

OUTPUT_DIR: "/data/training/wolf_final"
