

MODEL:
  FEATURE_DIM: 32


INPUT:
  SIZE_TRAIN: [720,450]
  SIZE_TEST: [720,450]
  NEAR_FAR_SIZE: [5.0, 19.0, 1]
  USE_RGB: False

DATASETS:
  TRAIN: "/data/dataset/Hairstyle2"
  FRAME_NUM: 1
  MASK: True
  CENTER: [543,924, 555,778, 541,730, 563,439, 558,527, 472,887, 641,964]
  SHIFT: 10
  MAXRATION: 0.5
  ROTATION: 0.0


SOLVER:
  OPTIMIZER_NAME: "Adam"
  BASE_LR: 0.00005
  WEIGHT_DECAY: 0.00002
  IMS_PER_BATCH: 3
  WARMUP_FACTOR: 0.333
  WARMUP_ITERS: 20
  WARMUP_METHOD: "linear"
  MAX_EPOCHS: 1500

TEST:
  IMS_PER_BATCH: 256

OUTPUT_DIR: "/data/training/50_145_283_2_1"
